[package]
name = "some_platformer_client"
version = "0.1.0"
authors = ["Gregory Obanos <gregory.obanos@gmail.com>", "Olivier Pinon <oliv.pinon@gmail.com"]

[dependencies]
ggez = "*"
log = "*"
flexi_logger = "*"
tokio = "*"
futures = "*"

some_platformer_lib = { path = "../lib" }