[package]
name = "some_platformer"
version = "0.1.0"
authors = ["Gregory Obanos <gregory.obanos@gmail.com>", "Olivier Pinon <oliv.pinon@gmail.com"]

[dependencies]
ggez = "*"
log = "*"
flexi_logger = "*"
specs = "*"
nalgebra = "*"