[package]
name = "some_platformer_server"
version = "0.1.0"
authors = ["Grégory OBANOS <gregory.obanos@gmail.com>"]

[dependencies]
tokio = "*"
tokio-io = "*"
futures = "*"
bytes = "*"

log = "*"
flexi_logger = "*"

some_platformer_lib = { path = "../lib" }